# Generated by Django 4.0.6 on 2022-08-16 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_student_roll'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together=set(),
        ),
    ]
